version: "3.7"

services:
    web1:
      build: .
      environment:
        - PORT=${PORT1}
      expose:
        - ${PORT1}
      networks:
        - internal_network
    web2:
      build: .
      environment:
        - PORT=${PORT2}
      expose:
        - ${PORT2}
      networks:
        - internal_network
    nginx:
      image: nginx
      depends_on:
        - web1
        - web2
      volumes:
        - ./nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
        - 8080:80
      networks:
        - internal_network
        - external_network

networks:
  external_network:
    name: external_network

  internal_network:
    external: false
    name: internal_network